### ISSUE TITLE
Support POST method

### ISSUE THREAD

**Issue by miere** [lopht/upload-maven-plugin#9]
Hi guys.

In most of cases I should work with uploads, the server expects a POST instead of PUT. It would be useful if we could configure which HTTP Method we will use to send files to the server.

Regards

**Comment by jgeorgeson** [comment]
Seems reasonable, I'll try to find some time for it but might be a few weeks before I can.

**Comment by jgeorgeson** [comment]
I'm planning on adding a true/false parameter to use POST instead of PUT. Will that suit your needs?

**Comment by miere** [comment]
Yeap! It works for me! ;)

**Comment by jgeorgeson** [comment]
0.5.0 has been deployed to jCenter and should be mirroring to Maven Central within next couple of of hours. Thanks for the suggestion.
